### ISSUE TITLE
SETUP_TYPE=MANUAL is not respected

### ISSUE THREAD

**Issue by the-nic** [tiredofit/docker-traefik#2]
On branch 2.2, when setting `SETUP_TYPE=MANUAL` the init script still writes the config, namely everything from the `log:` section is still written into `config.yaml`. It looks like the nested ifs are not really working as expected ;-)

The only way to hinder the startup script from writing the config is by mounting the config read-only.

**Comment by tiredofit** [comment]
Thanks for the report. I'll look into in the next couple of days as resolve.

**Comment by tiredofit** [comment]
Hi I just did a fresh build of this and ran the image with the environment variable setting and not seeing anything related to the configuration being written into config.yml. What I did see however is the traefik-certs-dumper throwing errors becuase it had nothing to base upon, so if wanting to start completely from scratch you will want to have that disabled.

I also found that logrotate throws errors in this fashion as well. In this case I would be setting `ENABLE_LOGROTATE=FALSE` as an environment variable.

Basically why the AUTO and MANUAL features exist is that they were intended to give a working solution of some applications based on defaults and how I use the image personally. After the first couple times of using the tool, its natural someone may want to do things to it that I haven't accounted for in the auto configuration setup. That is when we'd switch it over to SETUP_TYPE=MANUAL and make the changes so that they persisted through container start and stops. 

Can you get me full container startup logs if you are still seeing it writing to the config.yml? You can do this by setting DEBUG_MODE=TRUE. It will be alot of logs, but it can help determine just what is happening. Lesser verbosity is also possible with `CONTAINER_LOG_LEVEL=DEBUG`, but would only use with `DEBUG_MODE=FALSE`.

**Comment by the-nic** [comment]
Here is a startup log with `DEBUG_MODE=TRUE`: [debug.log](https://github.com/tiredofit/docker-traefik/files/5095071/debug.log)

image: tiredofit/traefik:2.2-latest

environment variables are:
```
    environment:
    - ZABBIX_HOSTNAME=traefik-app
    - ENABLE_HTTPS=TRUE
    - ENABLE_HTTPS_UPGRADE=TRUE
    - ENABLE_LETSENCRYPT=FALSE
    - DASHBOARD_HOSTNAME=traefik.example
    - ENABLE_DASHBOARD_AUTHENTICATION=FALSE
    - SETUP_TYPE=MANUAL
```

**Comment by tiredofit** [comment]
Many thanks for the log. I was able to determine where the problem occurred.
New build will be available on Docker Hub shortly:
`2.2-latest`
`latest`
`2.2-1.0.15`

Please let me know if you are seeing the same results!

**Comment by tiredofit** [comment]
Images are live

**Comment by the-nic** [comment]
yep, the errors are gone, thanks!
