### ISSUE TITLE
zabbix agent: jq missing, password may not contain special characters

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-traefik#8]
Sorry to detect more things, this time for the zabbix agent:

- jq is missing (apk add jq helped)
- curl fails when the admin password contains special characters like !

**Comment by tiredofit** [comment]
No need to apologize, I like that these things are being found.

I pulled JQ out of the base image a while ago and swapped it for YQ, and must have missed this one. I can add that one back in easy enough. As for the characters, I'm going to investigate a couple ideas which actually may help overall with leaking credentials to the system. I only have a few minutes this morning and then will return back to it in the afternoon.

**Comment by tiredofit** [comment]
- I've added jq back in - I at later date want to switch to `yq` which should be easy enough with swapping out the jq statements with `yq -o json ...`

- I've changed the way that curl uses authentication, instead it writes to a temp file and gets read on demand so it doesn't leak the credentials to the process list. Give it a try.

I'm looking at this script and it's been a while since I've used it. I don't even know if it works to be honest on these later Traefik versions. I am open to looking into it more if that is the case.

**Comment by tiredofit** [comment]
Looking into this further - yes this is for Traefik 1 and I have forgotten completely about it. I will add Prometheus metrics support into the image. This looks like it would take quite some time to build a Zabbix template for with LLD.

**Comment by joergmschulz** [comment]
so I've been wildgoose chasing on this one - the URL /health doesn't exist any longer.... didn't see any current zabbix script for traefik . 
So - let's close this one as well because it can't work currently.

**Comment by tiredofit** [comment]
I have a new build now that supports metrics - it hasn't been tagged as a release. It outputs quite a lot of metrics at this time I don't have the time to build a template for it..

**Comment by tiredofit** [comment]
Now `2.9-2.10.0`
